<?@('header.php'); ?>
<?php @('session.php'); ?>

    <div class="container">
		<div class="margin-top">
			<div class="row">	
				<?php @('head.php'); ?>
			<div class="span2">		
               <?php @('user_sidebar.php'); ?>
			</div>	
			<div class="span12" style="max-width:948px;margin-left: 50px;max-height: 100%">
			  		
			<link rel="stylesheet" type="text/css" href="https://su-sso.strathmore.edu/web/css/main.css"><link rel="stylesheet" type="text/css" href="https://su-sso.strathmore.edu/web/css/susams.css"><link rel="stylesheet" type="text/css" href="https://su-sso.strathmore.edu/web/css/colorbox.css"><link rel="stylesheet" type="text/css" href="https://su-sso.strathmore.edu/web/css/tabbed-nav.css"><link rel="icon" href="https://su-sso.strathmore.edu/web/images/favicon.ico" type="image/x-icon"><script type="text/javascript" id="paramStaticContentBasePath">var BASE_PATH = 'https://su-sso.strathmore.edu/web';</script><script type="text/javascript" language="javascript" src="https://su-sso.strathmore.edu/web/js/utils.js"></script><script type="text/javascript" language="javascript" src="https://su-sso.strathmore.edu/web/js/jquery.min.js"></script><script type="text/javascript" src="https://su-sso.strathmore.edu/web/js/jquery-ui-custom.min.js"></script><script type="text/javascript" language="javascript" src="https://su-sso.strathmore.edu/web/js/jquery-ui-1.8.7.custom.min.js"></script><script type="text/javascript" language="javascript" src="https://su-sso.strathmore.edu/web/js/jquery.colorbox-min.js"></script><script type="text/javascript" language="javascript" src="https://su-sso.strathmore.edu/web/js/susams.js"></script></head>
			</div></div><a href="#" title="Download" style="padding-left: 50px;" id="paramCursoAcademico2" onclick="downloadAcademicYearMarks('2022-2023'); return false;"><img src="https://su-sso.strathmore.edu/web/images/icon_pdf.gif" width="15" height="15"> Download<link rel="stylesheet" type="text/css" href="https://su-sso.strathmore.edu/web/css/Alumnos.css"><div id="content"><h1 class="heading">Coursework Marks</h1><h4 class="heading" style="padding: 0px;" id="paramSyllabus">BICS(April)-18</h4><hr width="90%" style="margin-left: 50px;"><div style="float: right; margin-right: 150px; padding-bottom: 25px;">
	</a><form name="frmMarks" id="frmMarks" action="./lifecycle/coursework/Marks.html" method="post"><input type="hidden" name="Command" id="inpCommand" value=""><input type="hidden" name="inpExpediente" id="paramExpediente" value="250815"><input type="hidden" name="inpAcademicYear" id="inpAcademicYear" value=""><div class="Centrado"><table border="0" cellpadding="2" cellspacing="4" width="80%" align="center"><tbody><tr><td width="10%" class="FondoGris Centrado"><span>KEY:</span></td><td width="30%" class="provisional"><span>Provisional</span></td><td width="30%" class="definitiva"><span>Final</span></td><td width="30%" class="certificable"><span>Registered</span></td></tr></tbody></table><div id="sectionCalificaciones" class="Centrado"><div class="Centrado"><center><table border="0" cellpadding="2" cellspacing="4" width="80%" class="Cabecera"><tbody><tr class="cabecera"><td colspan="2" width="40%"><div class="centrado"><table border="0" cellspacing="8" width="100%" class="Cabecera"><tbody><tr class="cabecera"><td colspan="4" width="60%" class="cabecera"><span class="negrita"> Academic Year: </span><span class="Negrita">2022-2023</span></td></tr></tbody></table></div></td><td colspan="3" width="60%" class="Cabecera"><div class="Centrado"><table border="0" cellspacing="8" width="100%" class="Cabecera"><tbody><tr><td colspan="4" width="60%" class="Cabecera"><span class="Negrita">Semester: <span>FIRST SEMESTER</span></span></td></tr></tbody></table></div></td></tr></tbody></table></center></div><div id="sectionCoursework">

</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><table width="80%" cellpadding="0" cellspacing="4" class="FondoGrisSuave BordeFino" align="center"><tbody><tr><td width="3%" rowspan="2" class="FondoGris"></td><td width="30%" rowspan="2" class="FondoGris Centrado"><span class="Negrita">Subject</span></td><td colspan="2" class="FondoGris Centrado"><span class="Negrita">Ordinary</span></td><td colspan="2" class="FondoGris Centrado"><span class="Negrita">Supplementary</span></td></tr><tr><td width="4%" class="FondoGris Centrado"><font size="2">Attempt No.</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Mark</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Attemp No.</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Mark</font></td></tr><tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Computer Organization and Architecture</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">49.5</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Participation</span></font></td><td align="right"><span>13/25</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Assignment</span></font></td><td align="right"><span>15.5/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>16.5/27</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>24/27</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 1</span></font></td><td align="right"><span>12/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 2</span></font></td><td align="right"><span>15/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 3</span></font></td><td align="right"><span>16/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 4</span></font></td><td align="right"><span>14/15</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Data Structures and Algorithms</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">40.2</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Assignment</span></font></td><td align="right"><span>8/10</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>15/31</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>3/25</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Object Oriented Programming II</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">50.67</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Class Assignment</span></font></td><td align="right"><span>22/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Semester Mini-Project</span></font></td><td align="right"><span>22/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT Two</span></font></td><td align="right"><span>22/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT One</span></font></td><td align="right"><span>11/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Principles of Ethics</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">50.25</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CLASS PRESENTATION</span></font></td><td align="right"><span>7.5/10</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 3- PRISON VISIT REPORT</span></font></td><td align="right"><span>9/10</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>11/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 4</span></font></td><td align="right"><span>6/10</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>17.5/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Probability Statistics I</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">35.67</span></b></td><td class="FondoGrisSuave Centrado"><span>-</span></td><td class=""><span>--</span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>11/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>12/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>ASSIGNMENTS</span></font></td><td align="right"><span>15/15</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Spanish I</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">74.47</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span></span></font></td><td align="right"><span>92/</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>65.1/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>66/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 3</span></font></td><td align="right"><span>92/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Attendace</span></font></td><td align="right"><span>100/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Participation</span></font></td><td align="right"><span>100/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Web Application Development</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="#FFDF7F" align="right"><b><span style="color: black;">49.4</span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>6/25</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>20/50</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Classroom Assignments</span></font></td><td align="right"><span>80/80</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Final Project</span></font></td><td align="right"><span>100/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>


</tbody></table>
<div class="Centrado"><center><table border="0" cellpadding="2" cellspacing="4" width="80%" class="Cabecera"><tbody><tr class="cabecera"><td colspan="2" width="40%"><div class="centrado"><table border="0" cellspacing="8" width="100%" class="Cabecera"><tbody><tr class="cabecera"><td colspan="4" width="60%" class="cabecera"><span class="negrita"> Academic Year: </span><span class="Negrita">2022-2023</span></td></tr></tbody></table></div></td><td colspan="3" width="60%" class="Cabecera"><div class="Centrado"><table border="0" cellspacing="8" width="100%" class="Cabecera"><tbody><tr><td colspan="4" width="60%" class="Cabecera"><span class="Negrita">Semester: <span>SECOND SEMESTER</span></span></td></tr></tbody></table></div></td></tr></tbody></table></center></div><div id="sectionCoursework">

</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><div id="sectionAsignatura">
</div><table width="80%" cellpadding="0" cellspacing="4" class="FondoGrisSuave BordeFino" align="center"><tbody><tr><td width="3%" rowspan="2" class="FondoGris"></td><td width="30%" rowspan="2" class="FondoGris Centrado"><span class="Negrita">Subject</span></td><td colspan="2" class="FondoGris Centrado"><span class="Negrita">Ordinary</span></td><td colspan="2" class="FondoGris Centrado"><span class="Negrita">Supplementary</span></td></tr><tr><td width="4%" class="FondoGris Centrado"><font size="2">Attempt No.</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Mark</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Attemp No.</font></td><td width="4%" class="FondoGris Centrado"><font size="2">Mark</font></td></tr><tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Advanced Networking</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span></span></font></td><td align="right"><span></span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Digital Logic</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 3</span></font></td><td align="right"><span>8/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Assignment 1</span></font></td><td align="right"><span>18.5/25</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>13/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>26/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 2</span></font></td><td align="right"><span>19/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Lab 1</span></font></td><td align="right"><span>16/20</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Internet Application Programming</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span></span></font></td><td align="right"><span></span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Operating Systems</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT One</span></font></td><td align="right"><span>13/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT Two</span></font></td><td align="right"><span>23/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Continuous Quick Quizzes Total</span></font></td><td align="right"><span>16/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Probability Statistics II</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>7/10</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>26/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Software Engineering</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT1</span></font></td><td align="right"><span>15.5/45</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Progress Presentations</span></font></td><td align="right"><span>34.5/40</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Final Presentations</span></font></td><td align="right"><span>28/30</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT2</span></font></td><td align="right"><span>51/65</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>

<tr><td colspan="2"><span style="font-weight: bold; display:block; font-size: 12px;">Spanish II</span></td><td class="FondoGrisSuave Centrado"><span>1</span></td><td bgcolor="" align="right"><b><span style="color: black;"></span></b></td><td class="FondoGrisSuave Centrado"><span>2</span></td><td class=""><span></span></td></tr><tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>La receta</span></font></td><td align="right"><span>90/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Describir a una persona</span></font></td><td align="right"><span>90/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 2</span></font></td><td align="right"><span>55/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>CAT 1</span></font></td><td align="right"><span>44.5/60</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>
<tr><td class="FondoGrisMuySuave">&nbsp;</td><td class="FondoGrisMuySuave" colspan="2"><font size="2"><span>Mi ciudad</span></font></td><td align="right"><span>90/100</span></td><td class="FondoGrisMuySuave centrado"></td><td class=""></td></tr>


</tbody></table>
</div><table border="0" cellpadding="2" cellspacing="4" width="80%" align="center"><tbody><tr><td width="10%" class="FondoGris Centrado"><span>KEY:</span></td><td width="30%" class="provisional"><span>Provisional</span></td><td width="30%" class="definitiva"><span>Final</span></td><td width="30%" class="certificable"><span>Registered</span></td></tr></tbody></table><br><br></div></form></div>

</div><div align="center" style="color: grey; size: 6px;"> Copyright © 
							
							
					<?php @('grading.php'); ?>		
		</div>
			</div>
		</div>
    </div>
<?php @('footer.php') ?>